### ISSUE TITLE
how to load a local pdb file?

### ISSUE THREAD

**Issue by luwei0917** [molstar/mol-view-spec#18]
this might be a very basic question. but I tried replacing builder.download with builder.parse_file, but doesn't work.
Thanks.

**Comment by JonStargaryen** [comment]
Hi @luwei0917,

the builder only supports `.download()` and can't make use of local files. Your structure data must be publicly available via some URL. That's the only way for the specification to work when shared with other people who won't have access to your local file.

Hope that helps,
Sebastian

**Comment by Raiyan-Rizwan** [comment]
Hi,
I was using Amazon AWS to host my protein and cluster files. Subsequently, I am downloading them on MolViewSpec from AWS, customizing the visual and finally visualizing them through an HTML file which I am also hosting on AWS. However, I am keeping the bucket where my protein files are stored as public, as such the files are accessible by anyone with the link. I was wondering if there was a way to privatize the protein files or at least establish some type of protection which keeps random people from finding and downloading the files, while also having the protein files processable by MolViewSpec.
