### ISSUE TITLE
Is this type correct?

### ISSUE THREAD

**Issue by zachcp** [molstar/mol-view-spec#30]
The `component` function has a `ColorInlineParams` type check which seems off.  [Link here](https://github.com/molstar/mol-view-spec/blob/master/molviewspec/molviewspec/builder.py#L309)
![image](https://github.com/user-attachments/assets/7c99aa1b-53b4-419b-b132-7c0ade4c2b1c)

**Comment by zachcp** [comment]
I think this should be `ComponentInlineParams`

**Comment by JonStargaryen** [comment]
Nice find and thank you for the PR.
