### ISSUE TITLE
FYI: PSE--> MVSJ

### ISSUE THREAD

**Issue by zachcp** [molstar/mol-view-spec#32]
Hi Team MolViewSpec,

I've begun a project to teach myself RUST.  The [pseutils](https://github.com/zachcp/pseutils) rust tool can load a pymol session file (`pse`) and output a folder with a an `msvj` file that can be immediately loaded as a webpage.  Currently the utility recognized pymol structure objects and selections only but I think its in a decent place to where it could be extended to add features. So I'm posting here mostly to see if this is a tool people like and would use but I have also begun to notice some issues.

- Selections in pymol are **named(( but in msvj->molstar they look like `ComponentExpression(){...json here....}`  Is there a naming mechanism for Components?
- There are only [3 representation types](https://github.com/molstar/mol-view-spec/blob/master/molviewspec/molviewspec/nodes.py#L155) in python I see other types, for example [this one](https://molstar.org/viewer/?snapshot-url=https%3A%2F%2Fmolstar.org%2Fdemos%2Fstates%2Fnpc.molx&snapshot-url-type=molx) uses `putty`.
- I don't yet have a great way to convert molecule level settings - right now I can access global settings and per atom settings so I think for maximum reproducibility I would need to implement some conversion functions between atoms and higher level objects.
- Is there a way in MVSJ to color by secondary structure?
- right now my pymol-> to PDB is primitive and doesn't handle complicated cases - e.g. many structures/models in an object.

Thanks again for this great software and documentation.
zach cp

**Comment by dsehnal** [comment]
Hi Zach,

this is very cool!

> * Selections in pymol are **named(( but in msvj->molstar they look like `ComponentExpression(){...json here....}`  Is there a naming mechanism for Components?

No, there is no naming. If you need the same selection more than once, you just copy it multiple times. We also support defining the selection from separate data files and there is caching when fetching it.

> * There are only [3 representation types](https://github.com/molstar/mol-view-spec/blob/master/molviewspec/molviewspec/nodes.py#L155) in python I see other types, for example [this one](https://molstar.org/viewer/?snapshot-url=https%3A%2F%2Fmolstar.org%2Fdemos%2Fstates%2Fnpc.molx&snapshot-url-type=molx) uses `putty`.
> 

The current MVS specification is very minimal, we can add support for more representations as well. Apart from `putty`, any others you find useful?

> * I don't yet have a great way to convert molecule level settings - right now I can access global settings and per atom settings so I think for maximum reproducibility I would need to implement some conversion functions between atoms and higher level objects.

Can you be more specific here?

> 
> * Is there a way in MVSJ to color by secondary structure?

Currently, you would have to be specific and supply per-residue colors yourself.

> * right now my pymol-> to PDB is primitive and doesn't handle complicated cases - e.g. many structures/models in an object.

Still a very cool use case!

**Comment by zachcp** [comment]
Thank you  @dsehnal . I think you've answered all my questions. The most direct way to transfer styles seems to be at the atom-level. I know how to to do that code-wise but it would result in a lot of JSON - not ideal. I will probably park this for the moment and add/build as needed. 

Thanks again for MVSJ - i think its a great project.

**Comment by dsehnal** [comment]
You can generate "object of arrays" JSON too, e.g.:

```json
{
  label_asym_id: ['A', 'B'],
  color: [0x00FF00, 0xFF0000],
}
```

Compressing this with GZip will make it very small. Similarly, the annotation data could be a binaryCIF file which would make it even smaller.

**Comment by zachcp** [comment]
Nice tip! Thanks. Yeah that would be much better.
