### ISSUE TITLE
Enhancement suggestion: membrane planes

### ISSUE THREAD

**Issue by cycle20** [molstar/mol-view-spec#33]
Hi,
This mvs approach is a very great idea. We would like to upgrade our visualization solution based on it.
(our Mol*-based application: https://pdbtm.unitmp.org/entry/1a0s)
Only one feature missing for it as I see: the membrane plane representation.
It would be good to provide its fine grained settings by annotation files or scene state descriptor.
(rim and plane centroid, radius etc.)
Is it possible to add it to the requirement list of the next MVS version?
Thank you,
Csongor

**Comment by dsehnal** [comment]
Hi, glad you like it.

We plan to add support for geometry primitives which would enable this. We will discuss the implementation priority for this at our next sync in couple weeks.

**Comment by cycle20** [comment]
Thank you

**Comment by cycle20** [comment]
> We plan to add support for geometry primitives which would enable this. We will discuss the implementation priority for this at our next sync in couple weeks.

Hi, David!

Is there any news regarding this enhancement?

**Comment by dsehnal** [comment]
Yes, we have started the implementation this week.

**Comment by cycle20** [comment]
Thank you very much. This is very good news.
I will check the repo notifications.
Best regards,
Csongor
